markdown: kramdown
permalink: /:title/
url: http://gitzx.github.io
name: www.etanote.com 
author: gitzx
email: gitzx@foxmail.com
duoshuo: etanote
cnzz: 
github: http://github.com/gitzx
pygments: true
safe: true
paginate: 20
about: "不积跬步，无以至千里 <br /><br /><br />"
