markdown: kramdown
permalink: /:title/
url: http://gitzx.github.io
name: www.etanote.com 
author: gitzx
email: gitzx@foxmail.com
duoshuo: gitzx
cnzz: 
github: http://github.com/gitzx
pygments: false
highlighter: rouge
safe: true
paginate: 15
about: "不积跬步，无以至千里 <br /><br /><br />"
